dist: bionic
language: csharp
solution: Flintr.sln
dotnet: 3.1.302
install:
  - nuget install NUnit.Console -Version 3.12.0-beta1 -OutputDirectory testrunner
  - choco install docfx
script:
  - dotnet restore
  - msbuild /p:Configuration=Release Flintr.sln
  - dotnet test
before_deploy:
  - docfx ./Flintr-lib/
deploy:
  provider: pages
  edge: true
  cleanup: false
  keep_history: false
  github_token: $GITHUB_TOKEN
  local_dir: ./Flintr-lib/_site
  on:
    branch: master