language: csharp
solution: Flintr.sln
dotnet: 3.1.302
install:
  - nuget install NUnit.Console -Version 3.12.0 -OutputDirectory testrunner
script:
  - dotnet restore
  - mono ./testrunner/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe ./Flintr-Runner-Test/bin/Release/netcoreapp3.1/Flintr-Runner-Test.dll